services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_api"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: siixo/todo-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # IMPORTANT: l’API lit DATABASE_URL via process.env.DATABASE_URL
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo_api
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  pgdata:
